
<?php 

	//print_r($oorder);	
	//exit();
	
 ?>

<div id="account" data-oorder-id="<?= $oorder->oorder_id; ?>">
	
	<div class="row title-row">
		<div class="col-sm-6">
			<h1>
				<a href="/account/" class="btn-back"><i class="icon icon-arrow-circle-o-left icon-lg"></i></a> 
				&nbsp;&nbsp;Order #<?= $oorder->oorder_id; ?> &nbsp; 
				<?php if( $_SESSION["ouser"]->ouser_permission_level == 0 ){ ?> 
				<select id="select-oorder-status" name="oorder_status_id" class="form-control">
					<?php forEach( $statuses as $i => $status ){?>
					<option value="<?= $i ?>" <?= ($i==$oorder->oorder_status_id)?'SELECTED="SELECTED"':''; ?>><?= $status ?></option>
					<?php } ?>
				</select>
				<?php } else { ?> 
				<span class="text-success"><?= $this->route('/m/orders/oOrders/getOptions/?column=oorder_status_id&key='.$oorder->oorder_status_id)->data; ?></span>
				<?php } ?>
			</h1>
		</div>
		<div class="col-sm-6">
			<h4 class="text-right"><?= date('d M Y h:i:s A',strtotime($oorder->oorder_date) ); ?></h4>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-12"><hr/></div>
	</div>
	
	
	<div class="row header-row">
		
		<div class="col-sm-4">
			<h2><i class="icon icon-user"></i> &nbsp;Customer</h2>
		</div>
		
		<div class="col-sm-4">
			<h2><i class="icon icon-dropbox"></i> Ship To</h2>
		</div>
		
		<div class="col-sm-4">
			<h2><i class="icon icon-credit-card-alt"></i> &nbsp;Billing</h2>
		</div>
		
	</div>
	
	<div class="row">
		<div class="col-sm-12"><hr/></div>
	</div>
	
	<div class="row header-body">
		
		<div class="col-sm-4">
			<address>
				<?= $oorder->customer[0]->ocustomer_name; ?><br/>
				<?= $oorder->customer[0]->ocustomer_email; ?><br/>
				<?= $oorder->customer[0]->ocustomer_phone; ?><br/>
			</address>
		</div>
		
		<div class="col-sm-4">
			<address>
				<?= $oorder->shipTo[0]->oaddress_name; ?><br/>
				<?= $oorder->shipTo[0]->oaddress_street_1; ?><br/>
				<?= !empty($oorder->shipTo[0]->oaddress_street_2)?$oorder->shipTo[0]->oaddress_street_2.'<br/>':''; ?>
				<?= $oorder->shipTo[0]->oaddress_city . ' ' . $oorder->shipTo[0]->oaddress_state . ', ' . $oorder->shipTo[0]->oaddress_zip; ?><br/>
			</address>
		</div>
		
		<div class="col-sm-4">
			<address>
				<?php switch( strtolower($oorder->card[0]->ocard_type) ){
					case 'visa': echo '<i class="icon icon-cc-visa icon-lg"></i> &nbsp;VISA<br/>'; break;
					case 'mastercard': echo '<i class="icon icon-cc-mastercard icon-lg"></i>  &nbsp;MasterCard<br/>'; break; 
					case 'discover': echo '<i class="icon icon-cc-discover icon-lg"></i>  &nbsp;DISCOVER<br/>'; break; 
					case 'american express': echo '<i class="icon icon-cc-amex icon-lg"></i>  &nbsp;American Express<br/>'; break; 
					case 'jcb': echo '<i class="icon icon-cc-jcb icon-lg"></i>  &nbsp;JCB<br/>'; break; 
					case 'diners club': echo '<i class="icon icon-cc-diners-club icon-lg"></i>  &nbsp;Diners Club<br/>'; break; 
				} ?>
				****-****-****-<?= $oorder->card[0]->ocard_last_four; ?><br/>
				
			</address>
		</div>
		
	</div>
	
	<div class="row">
		<div class="col-sm-12"><hr/></div>
	</div>
	
	<div class="row header-row">
		
		<div class="col-sm-12">
			<h2>&nbsp; <i class="icon icon-list-ul"></i> &nbsp;Services Ordered</h2>
		</div>
		
	</div>
	
	<div class="row">
		<div class="col-sm-12"><hr/></div>
	</div>
	
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Item</th>
				<th>Qty</th>
				<th class="text-right">Total</th>
			</tr>
		</thead>
		<tbody>
			<?php forEach( $oorder->items as $oitem ){ ?>
			<tr>
				<td>
					<span class="parent-title"><?= $oitem->oorder_item_parent_description; ?></span><br/>
					<span class="child-title"><?= $oitem->oorder_item_description; ?></span>
				</td>
				<td><?= $oitem->oorder_item_quantity; ?></td>
				<td class="text-right"><?= $oitem->oorder_item_total; ?></td>
			</tr>
			<?php if( !empty($oitem->watches) ){ ?>
			<tr>
				<td colspan="3">
					<div class="watch-rows">
						<div class="row">
							<div class="col-sm-12">
								<h4><i class="icon icon-clock-o"></i> &nbsp;Watches to be Serviced</h4>
							</div>
							<div class="col-sm-2">
								<strong>Brand:</strong><br/>
							</div>
							<div class="col-sm-2">
								<strong>Serial Number:</strong> <br/>					
							</div>
							<div class="col-sm-2">
								<strong>Caseback</strong>
							</div>
							<div class="col-sm-6">
								<strong>Condition</strong>
							</div>
						</div>
						<?php forEach( $oitem->watches as $owatch ){ ?>
						<div class="row">
							<div class="col-sm-2">
								 <?= $owatch->owatch_brand; ?>
							</div>
							<div class="col-sm-2">
								<?= $owatch->owatch_serial_number; ?>
							</div>
							<div class="col-sm-2">
								<?= $owatch->owatch_caseback_number; ?>
							</div>
							<div class="col-sm-6">
								<?= $owatch->owatch_condition; ?>
							</div>
						</div>
						<?php } ?>
					</div>
				</td>
			</tr>
			<?php } } ?>
		</tbody>
	</table>
		
	</table>
	
	
	<div class="row item-row">
		<div class="col-sm-8">

			
			
		</div>
		<div class="col-sm-2">
			Qty: &nbsp;
		</div>
		<div class="col-sm-2 text-right">
			$ 
		</div>
	</div>
	
	
	<div class="row">
		<div class="col-sm-12"><hr/></div>
	</div>
	
	<div class="row header-row">
		
		<div class="col-sm-12">
			<h2>&nbsp; <i class="icon icon-money"></i> &nbsp;Payments</h2>
		</div>
		
	</div>
	
	<div class="row">
		<div class="col-sm-12"><hr/></div>
	</div>
	
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th>Description</th>
				<th>Date</th>
				<th class="text-center">Status</th>
				<th class="text-right">Total</th>
			</tr>	
		</thead>
		<tbody>
			<?php forEach( $oorder->payments as $opayment ){ ?>
			<tr>
				<td>Order description.</td>
				<td>25 Feb 2015</td>
				<td class="text-center">Paid</td>
				<td class="text-right">$ <?= $opayment->opayment_total; ?></td>
			</tr>
			<?php } ?>
		</tbody>
	</table>
	
	<div class="row">
		<div class="col-sm-12"><hr/></div>
	</div>
	
	<div class="row header-row">
		
		<div class="col-sm-12">
			<h2>&nbsp; <i class="fa fa-envelope"></i> &nbsp;Messages</h2>
		</div>
		
	</div>
	
	<div class="row">
		<div class="col-sm-12"><hr/></div>
	</div>
	
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Sent</th>
				<th>From</th>
				<th class="text-center">Message</th>
			</tr>	
		</thead>
		<tbody>
			<?php forEach( $omail as $m ){ ?>
			<tr>
				<td style="width:20%"><?= date("d M Y",strtotime($m->omail_datetime_sent)); ?></td>
				<td style="width:20%"><?= ($m->ouser_from==7)?'Customer Care':$oorder->customer[0]->ocustomer_name; ?></td>
				<td class="text-left">
					<h4><?= $m->omail_subject; ?></h4>
					<p><?= str_replace("\n","<br/>",$m->omail_message); ?></p>
				</td>
			</tr>
			<?php } ?>
		</tbody>
	</table>
	
	<div class="row">
		<div class="col-sm-12">
			<br/>
			<form id="frm-omail">
				
				<input type="hidden" name="oorder_id" value="<?= $oorder->oorder_id; ?>" ?>
				<input type="hidden" name="ouser_from" value="<?= $_SESSION["ouser"]->ouser_id; ?>" ?>
				<input type="hidden" name="ouser_to" value="<?= ($_SESSION["ouser"]->ouser_id==7)?$oorder->customer[0]->ouser_id:7; ?>" ?>
				
				<div class="form-group clearfix credit-card">
					<label for="omail-subject" class="col-sm-offset-3 col-sm-2 control-label">Message Subject</label>
					<div class="col-md-7">
						<input type="text" class="form-control input-lg" id="omail-subject" name="omail_subject" placeholder="Enter Message Subject">
					</div>
				</div>
				
				<div class="form-group clearfix credit-card">
					<label for="omail-message" class="col-sm-offset-3 col-sm-2 control-label">Enter Message</label>
					<div class="col-md-7">
						<textarea rows="10" class="form-control input-lg" id="omail-mesage" name="omail_message" placeholder="Enter Message"></textarea>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" id="btn-billing" class="btn btn-primary btn-lg pull-right">&nbsp;&nbsp; <strong>Send</strong> &nbsp;<i class="icon icon-arrow-circle-o-right icon-lg"></i> &nbsp;&nbsp;</submit>
						<!--<button class="btn btn-default pull-right btn-lg previous" data-loading-text='<i class="icon icon-cog icon-spin"></i> Saving...'><i class="icon icon-arrow-circle-o-left icon-lg"></i> Previous</button>-->
					</div>
				</div>
			</form>
		</div>
	</div>

	
</div>