

<div id="receipt" class="row">
	<div class="col-sm-6"><h1>Receipt</h1></div>
	<div class="col-sm-6">
		<a href="/account/" class="btn btn-primary btn-lg pull-right">My Account <i class="fa fa-arrow-circle-o-right fa-lg"></i> </a>		
		<a href="/cart/receiptEmail/" target="_blank" class="btn btn-primary btn-lg pull-right"><i class="fa fa-print fa-lg"></i> &nbsp;Print</a>		
		
	</div>
</div>

<iframe src="/cart/receiptEmail/" height="600">
	
</iframe>


